var hierarchy =
[
    [ "AnalyticsHandler", "class_app_1_1_http_1_1_classes_1_1_analytics_1_1_analytics_handler.html", null ],
    [ "AudioVideoParser", "class_app_1_1_http_1_1_classes_1_1_audio_video_parser.html", null ],
    [ "Authorization", "class_app_1_1_http_1_1_middleware_1_1_authorization.html", null ],
    [ "AvoidCloudflareMinification", "class_app_1_1_http_1_1_middleware_1_1_main_domain_1_1_avoid_cloudflare_minification.html", null ],
    [ "BaseController", null, [
      [ "Controller", "class_app_1_1_http_1_1_controllers_1_1_controller.html", [
        [ "LangChainApiController", "class_app_1_1_http_1_1_controllers_1_1_api_1_1_lang_chain_api_controller.html", null ],
        [ "FileManagerController", "class_app_1_1_http_1_1_controllers_1_1_api_1_1_sites_1_1_hormel_1_1_file_manager_controller.html", null ],
        [ "LoginController", "class_app_1_1_http_1_1_controllers_1_1_auth_1_1_login_controller.html", null ],
        [ "HomeController", "class_app_1_1_http_1_1_controllers_1_1_home_controller.html", null ],
        [ "OpenAIController", "class_app_1_1_http_1_1_controllers_1_1_open_a_i_controller.html", null ],
        [ "DashboardController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_global_s_s_a_1_1_dashboard_controller.html", null ],
        [ "SSAContentTopicController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_global_s_s_a_1_1_s_s_a_content_topic_controller.html", null ],
        [ "SSAGlobalBrandController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_global_s_s_a_1_1_s_s_a_global_brand_controller.html", null ],
        [ "SSAGlobalContainerController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_global_s_s_a_1_1_s_s_a_global_container_controller.html", null ],
        [ "SSAGlobalDesingHuddleClassMap", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_global_s_s_a_1_1_s_s_a_global_desing_huddle_class_map.html", null ],
        [ "SSAGlobalGalleryController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_global_s_s_a_1_1_s_s_a_global_gallery_controller.html", null ],
        [ "SSAGlobalPageComponentController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_global_s_s_a_1_1_s_s_a_global_page_component_controller.html", null ],
        [ "SSAGlobalPagesController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_global_s_s_a_1_1_s_s_a_global_pages_controller.html", null ],
        [ "SSAGlobalSnippetsController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_global_s_s_a_1_1_s_s_a_global_snippets_controller.html", null ],
        [ "SSAGlobalTagsController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_global_s_s_a_1_1_s_s_a_global_tags_controller.html", null ],
        [ "SSAPromptController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_global_s_s_a_1_1_s_s_a_prompt_controller.html", null ],
        [ "SSAShortUrlController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_global_s_s_a_1_1_s_s_a_short_url_controller.html", null ],
        [ "SSAVariableController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_global_s_s_a_1_1_s_s_a_variable_controller.html", null ],
        [ "SiteController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_global_s_s_a_1_1_site_controller.html", null ],
        [ "SiteSubTopicContentController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_global_s_s_a_1_1_site_sub_topic_content_controller.html", null ],
        [ "UserProfileController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_global_s_s_a_1_1_user_profile_controller.html", null ],
        [ "SiteAnalyticsController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_analytics_controller.html", null ],
        [ "SiteCampaignController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_campaign_controller.html", null ],
        [ "SiteCoursesController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_courses_controller.html", null ],
        [ "SiteEmailController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_email_controller.html", null ],
        [ "SiteEmailTemplateController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_email_template_controller.html", null ],
        [ "SiteExtrasController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_extras_controller.html", null ],
        [ "SiteFormQuestionAnswerController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_form_question_answer_controller.html", null ],
        [ "SiteFormQuestionController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_form_question_controller.html", null ],
        [ "SiteFormsController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_forms_controller.html", null ],
        [ "SiteGalleryController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_gallery_controller.html", null ],
        [ "SiteGroupsController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_groups_controller.html", null ],
        [ "SiteMajorGroupController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_major_group_controller.html", null ],
        [ "MeetingEventController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_meetings_1_1_meeting_event_controller.html", null ],
        [ "SiteMeetingTimeSlotController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_meetings_1_1_site_meeting_time_slot_controller.html", null ],
        [ "SitePageComponentController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_page_component_controller.html", null ],
        [ "SitePagesController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_pages_controller.html", null ],
        [ "SiteRolesController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_roles_controller.html", null ],
        [ "SiteSettingController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_setting_controller.html", null ],
        [ "SiteSmsController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_sms_controller.html", null ],
        [ "SiteSmsFlowController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_sms_flow_controller.html", null ],
        [ "SiteSnippetController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_snippet_controller.html", null ],
        [ "SiteUiGridController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_ui_grid_controller.html", null ],
        [ "SiteUsersController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_users_controller.html", null ],
        [ "SiteVariableController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_tenant_1_1_site_variable_controller.html", null ],
        [ "TwoFactorAuthController", "class_app_1_1_http_1_1_controllers_1_1_site_super_admin_1_1_two_factor_auth_controller.html", null ],
        [ "GenericPasswordController", "class_app_1_1_http_1_1_controllers_1_1_subdomain_1_1_backend_1_1_auth_advance_1_1_generic_password_controller.html", null ],
        [ "TwoFactorAuthController", "class_app_1_1_http_1_1_controllers_1_1_subdomain_1_1_backend_1_1_auth_advance_1_1_two_factor_auth_controller.html", null ],
        [ "ConfirmPasswordController", "class_app_1_1_http_1_1_controllers_1_1_subdomain_1_1_backend_1_1_user_1_1_auth_1_1_confirm_password_controller.html", null ],
        [ "ForgotPasswordController", "class_app_1_1_http_1_1_controllers_1_1_subdomain_1_1_backend_1_1_user_1_1_auth_1_1_forgot_password_controller.html", null ],
        [ "LoginController", "class_app_1_1_http_1_1_controllers_1_1_subdomain_1_1_backend_1_1_user_1_1_auth_1_1_login_controller.html", null ],
        [ "RegisterController", "class_app_1_1_http_1_1_controllers_1_1_subdomain_1_1_backend_1_1_user_1_1_auth_1_1_register_controller.html", null ],
        [ "ResetPasswordController", "class_app_1_1_http_1_1_controllers_1_1_subdomain_1_1_backend_1_1_user_1_1_auth_1_1_reset_password_controller.html", null ],
        [ "VerificationController", "class_app_1_1_http_1_1_controllers_1_1_subdomain_1_1_backend_1_1_user_1_1_auth_1_1_verification_controller.html", null ],
        [ "VerificationCustomController", "class_app_1_1_http_1_1_controllers_1_1_subdomain_1_1_backend_1_1_user_1_1_auth_1_1_verification_custom_controller.html", null ],
        [ "DashboardController", "class_app_1_1_http_1_1_controllers_1_1_subdomain_1_1_backend_1_1_user_1_1_dashboard_controller.html", null ],
        [ "PageController", "class_app_1_1_http_1_1_controllers_1_1_subdomain_1_1_backend_1_1_user_1_1_page_controller.html", null ],
        [ "UserProfileController", "class_app_1_1_http_1_1_controllers_1_1_subdomain_1_1_backend_1_1_user_1_1_user_profile_controller.html", null ],
        [ "HomeController", "class_app_1_1_http_1_1_controllers_1_1_subdomain_1_1_frontend_1_1_home_controller.html", null ],
        [ "PageRequestFormController", "class_app_1_1_http_1_1_controllers_1_1_subdomain_1_1_frontend_1_1_page_request_form_controller.html", null ],
        [ "LoginController", "class_app_1_1_http_1_1_controllers_1_1_super_admin_1_1_auth_1_1_login_controller.html", null ],
        [ "DashboardController", "class_app_1_1_http_1_1_controllers_1_1_super_admin_1_1_dashboard_controller.html", null ],
        [ "MainPageController", "class_app_1_1_http_1_1_controllers_1_1_super_admin_1_1_main_page_controller.html", null ],
        [ "MainPagesController", "class_app_1_1_http_1_1_controllers_1_1_super_admin_1_1_main_pages_controller.html", null ],
        [ "UserController", "class_app_1_1_http_1_1_controllers_1_1_super_admin_1_1_user_controller.html", null ],
        [ "WebhookController", "class_app_1_1_http_1_1_controllers_1_1_system_1_1_webhook_controller.html", null ]
      ] ]
    ] ],
    [ "ClaudeService", "class_app_1_1_http_1_1_classes_1_1_ai_models_1_1_claude_service.html", null ],
    [ "ClientProtection", "class_app_1_1_http_1_1_middleware_1_1_subdomain_1_1_client_protection.html", null ],
    [ "ClientSiteChecker", "class_app_1_1_http_1_1_middleware_1_1_subdomain_1_1_client_site_checker.html", null ],
    [ "FrontendRenderProxy", "class_app_1_1_http_1_1_classes_1_1_services_1_1_frontend_render_proxy.html", null ],
    [ "GptAssistant", "class_app_1_1_http_1_1_classes_1_1_ai_models_1_1_gpt_assistant.html", null ],
    [ "GptService", "class_app_1_1_http_1_1_classes_1_1_ai_models_1_1_gpt_service.html", null ],
    [ "GuardSwitcher", "class_app_1_1_http_1_1_middleware_1_1_main_domain_1_1_super_and_site_super_admin_1_1_guard_switcher.html", null ],
    [ "HandleCors", "class_app_1_1_http_1_1_middleware_1_1_cors_1_1_handle_cors.html", null ],
    [ "HttpKernel", null, [
      [ "Kernel", "class_app_1_1_http_1_1_kernel.html", null ]
    ] ],
    [ "HuddleUserManager", "class_app_1_1_http_1_1_classes_1_1_design_huddle_1_1_huddle_user_manager.html", null ],
    [ "IsSitePrivate", "class_app_1_1_http_1_1_middleware_1_1_subdomain_1_1_is_site_private.html", null ],
    [ "IsSubdomainOwner", "class_app_1_1_http_1_1_middleware_1_1_main_domain_1_1_tenant_1_1_is_subdomain_owner.html", null ],
    [ "IsVerifyEmail", "class_app_1_1_http_1_1_middleware_1_1_subdomain_1_1_is_verify_email.html", null ],
    [ "Middleware", null, [
      [ "Authenticate", "class_app_1_1_http_1_1_middleware_1_1_authenticate.html", null ],
      [ "CheckForMaintenanceMode", "class_app_1_1_http_1_1_middleware_1_1_check_for_maintenance_mode.html", null ],
      [ "EncryptCookies", "class_app_1_1_http_1_1_middleware_1_1_encrypt_cookies.html", null ],
      [ "TrimStrings", "class_app_1_1_http_1_1_middleware_1_1_trim_strings.html", null ],
      [ "TrustProxies", "class_app_1_1_http_1_1_middleware_1_1_trust_proxies.html", null ],
      [ "VerifyCsrfToken", "class_app_1_1_http_1_1_middleware_1_1_verify_csrf_token.html", null ]
    ] ],
    [ "OptionsCors", "class_app_1_1_http_1_1_middleware_1_1_cors_1_1_options_cors.html", null ],
    [ "RedirectIfAuthenticated", "class_app_1_1_http_1_1_middleware_1_1_redirect_if_authenticated.html", null ],
    [ "ResetTenant", "class_app_1_1_http_1_1_middleware_1_1_main_domain_1_1_tenant_1_1_reset_tenant.html", null ],
    [ "SaImpersonateSsa", "class_app_1_1_http_1_1_middleware_1_1_main_domain_1_1_super_admin_1_1_sa_impersonate_ssa.html", null ],
    [ "SiteSuperAdminProtection", "class_app_1_1_http_1_1_middleware_1_1_main_domain_1_1_super_and_site_super_admin_1_1_site_super_admin_protection.html", null ],
    [ "SnippetDataParser", "class_app_1_1_http_1_1_classes_1_1_snippet_data_parser.html", null ],
    [ "SsaAdminImpersonate", "class_app_1_1_http_1_1_middleware_1_1_subdomain_1_1_ssa_admin_impersonate.html", null ],
    [ "SsaTwoFactorAuth", "class_app_1_1_http_1_1_middleware_1_1_main_domain_1_1_super_and_site_super_admin_1_1_ssa_two_factor_auth.html", null ],
    [ "SuperAdminProtection", "class_app_1_1_http_1_1_middleware_1_1_main_domain_1_1_super_admin_1_1_super_admin_protection.html", null ],
    [ "TextToMp3", "class_app_1_1_http_1_1_classes_1_1_text_to_mp3.html", null ],
    [ "TextToSpeech", "class_app_1_1_http_1_1_classes_1_1_text_to_speech.html", null ],
    [ "TwoFactorAuth", "class_app_1_1_http_1_1_middleware_1_1_auth_1_1_two_factor_auth.html", null ],
    [ "UpdateDesignHuddleAccessToken", "class_app_1_1_http_1_1_middleware_1_1_main_domain_1_1_super_and_site_super_admin_1_1_update_design_huddle_access_token.html", null ],
    [ "UserProtection", "class_app_1_1_http_1_1_middleware_1_1_subdomain_1_1_user_protection.html", null ],
    [ "Component", null, [
      [ "BluePrintForm", "class_app_1_1_http_1_1_livewire_1_1_blue_print_form.html", null ],
      [ "ChatComponent", "class_app_1_1_http_1_1_livewire_1_1_chat_component.html", null ],
      [ "GalleryComponent", "class_app_1_1_http_1_1_livewire_1_1_gallery_component.html", null ],
      [ "TopicSubTopicContent", "class_app_1_1_http_1_1_livewire_1_1_global_content_1_1_topic_sub_topic_content.html", null ],
      [ "BluePrintForm", "class_app_1_1_http_1_1_livewire_1_1_global_page_1_1_blue_print_form.html", null ],
      [ "VirtualContainerEdit", "class_app_1_1_http_1_1_livewire_1_1_global_ssa_1_1_virtual_container_edit.html", null ],
      [ "VirtualPageEdit", "class_app_1_1_http_1_1_livewire_1_1_global_ssa_1_1_virtual_page_edit.html", null ],
      [ "PreviewIframe", "class_app_1_1_http_1_1_livewire_1_1_preview_iframe.html", null ],
      [ "FormSingleQuestion", "class_app_1_1_http_1_1_livewire_1_1_site_form_1_1_form_single_question.html", null ],
      [ "SsaGallery", "class_app_1_1_http_1_1_livewire_1_1_ssa_gallery.html", null ],
      [ "VimeoApiSearch", "class_app_1_1_http_1_1_livewire_1_1_vimeo_api_search.html", null ]
    ] ]
];